org: blesssan
app: aws-node-express-dynamodb-api
service: aws-node-starter
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    TOKEN: ${env:APP_TOKEN}
    WHATSAPP_BUSINESS_NUMBER_ID: ${env:WHATSAPP_BUSINESS_NUMBER_ID}
    ACCESS_TOKEN: ${env:ACCESS_TOKEN}
    REVIEW_TABLE: reviews
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:us-east-1:856364339827:table/${self:provider.environment.REVIEW_TABLE}
        - Effect: "Allow"
          Action:
            - firehose:DeleteDeliveryStream
            - firehose:PutRecord
            - firehose:PutRecordBatch
            - firehose:UpdateDestination
          Resource: arn:aws:firehose:us-east-1:856364339827:deliverystream/whatsapp-reviews

functions:
  wa_webhook:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"

plugins:
  - serverless-offline

useDotenv: true
